version: '3'

services:
  # app:
  #   container_name: indorse-app
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   build:
  #     context: ./app/
  #     dockerfile: Dockerfile
  #   links:
  #     - api
  #   volumes:
  #     - ./app:/app
  #     - ./app/public:/app/public
  #     - /app/node_modules

  development-db:
    container_name: indorse-db-development
    image: postgres:11.4-alpine
    restart: always
    environment:
      POSTGRES_DB: 'indorse_development'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
    ports:
      - 5432:5432

  api:
    container_name: indorse-api
    restart: always
    build: ./api/
    environment:
      - NODE_ENV=development
    ports:
      - 8080:9000
    depends_on:
      - development-db
    volumes:
      - ./api:/api
      - /api/node_modules
